server:
  _IP: RaspberryIES002.ost.ch
  port: 50024

client:
  windowMode: true
  developerMode: false

properties:
  freq:
    units: Hz
    default: 20000
    min: 1000
    max: 100000
  voltLvl:
    units: V
    default: 2
    min: 0.001
    max: 2
  nPrim:
    units: 'turns'
    default: 1
    min: 1
    max: 1000
  nSec:
    units: 'turns'
    default: 2
    min: 1
    max: 1000
  L1:
    units: H
  L2:
    units: H
  v1_prim:
    units: V
  v2_prim:
    units: V
  v1_sec:
    units: V
  v2_sec:
    units: V
  k:
    units: ''
  k1:
    units: ''
  k2:
    units: ''
  Ls1_prim:
    units: H
  Lm:
    units: H
  Ls2_prim:
    units: H
  Ls:
    units: H
  Lp:
    units: H
  N:
    units: ''

measurement_devices:
  coupMeas_DMM1: "TCPIP0::MMIES013.ost.ch::INSTR"
  coupMeas_DMM2: "TCPIP0::MMies017.ost.ch::INSTR"
  coupMeas_LCR: "TCPIP0::LMGies001.ost.ch::INSTR"