ip: RaspberryIES002.ost.ch
port: 50024

windowMode: true
developerMode: false

properties:
  freq:
    units: Hz
    default: 20000
    min: 1000
    max: 100000
  voltLvl:
    units: V
    default: 3
    min: 0.001
    max: 2
  nPrim:
    units: 'turns'
    default: 30
    min: 1
    max: 1000
  nSec:
    units: 'turns'
    default: 2
    min: 1
    max: 1000
  L1:
    units: H
  L2:
    units: H
  v1:
    units: V
  v2:
    units: V
  k:
    units: ''
  k1:
    units: ''
  k2:
    units: ''
  Ls1_prim:
    units: H
  Lm:
    units: H
  Ls2_prim:
    units: H
  Ls:
    units: H
  Lp:
    units: H
  N:
    units: ''
