client:
  developerMode: false
  windowMode: true
measurement_devices:
  _DMM1: TCPIP0::MMIES013.ost.ch::INSTR
  _DMM2: TCPIP0::MMies017.ost.ch::INSTR
  _LCR: TCPIP0::LMGies001.ost.ch::INSTR
properties:
  L1:
    units: H
  L2:
    units: H
  Lm:
    units: H
  Lp:
    units: H
  Ls:
    units: H
  Ls1_prim:
    units: H
  Ls2_prim:
    units: H
  freq:
    default: 20000
    max: 100000
    min: 1000
    units: Hz
  nPrim:
    default: 1
    max: 1000
    min: 1
    units: turns
  nSec:
    default: 2
    max: 1000
    min: 1
    units: turns
  v1_prim:
    units: V
  v1_sec:
    units: V
  v2_prim:
    units: V
  v2_sec:
    units: V
  voltLvl:
    default: 2
    max: 2
    min: 0.001
    units: V
server:
  _IP: RaspberryIES002.ost.ch
  port: 50024
